server:
  port: 8089
spring:
  application:
    name: inventory
  #  cloud:
  #    nacos:
  #      server-addr:127.0.0.1:8848
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD:}
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect.storage_engine: innodb
#        hbm2ddl.auto: update
  kafka:
    bootstrap-servers: localhost:9092
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

#logging:
#  level:
#    com.group16.item: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"

knife4j:
  enable: false
  openapi:
    title: Store order interface document
    description: "Store order interface document"
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.group16.order.controller