
server:
 port: 8085

spring:
  threads:
    virtual:
      enabled: true
  cloud.gateway.mvc:
    routes:
      - id: users-route
        uri: ${ALB_URI:http://localhost:8080}
        predicates:
        - Path=/**
        filters:
        # - PrefixPath=/api
      - id: orders-route
        uri: ${ALB_URI:http://localhost:8089}
        predicates:
        - Path=/**
        filters:
        # - PrefixPath=/api
      
logging:
  level:
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.web: TRACE

